# Generated by Django 4.2.5 on 2023-09-20 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('birthday', models.DateField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
